config/routes.rb
RentAHome::Application.routes.draw do
  
  devise_for :users

  root :to => 'static_pages#home'
  
  resources :properties do
    collection do
      get :search
    end
  end
    
  match ':action' => 'static_pages#:action'
  
 

end

app/models/bathroom.rb
class Bathroom < ActiveRecord::Base
  attr_accessible :bathroom
  
  validates(:bathroom, presence: true)
    
  has_many(:properties)
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :name
    
  validates(:name, presence: true)
    
  has_many(:properties)
end

app/models/county.rb
class County < ActiveRecord::Base
  attr_accessible :name
  
  validates(:name, presence: true)
    
  has_many(:properties)
end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  attr_accessible :pet
  
  validates(:pet, presence: true)
    
  has_many(:properties)
end

app/models/property.rb
class Property < ActiveRecord::Base
  attr_accessible :city, :state, :county, :zip, :room, :bathroom, :pet
  
  validates(:city, presence: true)
  validates(:state, presence: true)
  validates(:county, presence: true)
  validates(:zip, presence: true)
  validates(:room, presence: true)
  validates(:bathroom, presence: true)
  validates(:pet, presence: true)
  
  belongs_to(:city, :foreign_key => "city")
  belongs_to(:state, :foreign_key => "state")
  belongs_to(:county, :foreign_key => "county")  
  belongs_to(:zip, :foreign_key => "zip")
  belongs_to(:room, :foreign_key => "room")
  belongs_to(:bathroom, :foreign_key => "bathroom")
  belongs_to(:pet, :foreign_key => "pet")
  
end

app/models/rental.rb
class Rental < ActiveRecord::Base
  attr_accessible :rental_type
  
  validates(:rental_type, presence: true)
  
  has_many(:properties)
end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :room
  
  validates(:room, presence: true)
    
  has_many(:properties)
end

app/models/search.rb
class Search < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :name, :abbr
  
  validates(:name, presence: true)
  validates(:abbr, presence: true)
  
  has_many(:properties)
end
  

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/zip.rb
class Zip < ActiveRecord::Base
  attr_accessible :zip_code
  
  validates(:zip_code, presence: true)
  
  has_many(:properties)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index
    @properties = Property.where("zip = ?0", params[:zip_code])
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @homes }
    end    
  end
  
  def new
    @properties = Property.all
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @homes }
    end 
  end  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/property_helper.rb
module PropertyHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/application/_chromeframe.html.erb
<!--[if lt IE 7]>
  <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->

app/views/application/_footer.html.erb
<footer id="footer">
  <small class="copyright">
    Rent A Home, Copyright &copy; <%= Date.today.year %>
  </small>
</footer>

app/views/application/_head.html.erb
<head>
  <meta charset="utf-8">

  <%# Use the .htaccess and remove these lines to avoid edge case issues. %>
  <%# More info: h5bp.com/b/378 %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>Rent a Home</title>
  <meta name="description" content="">

  <%# Mobile viewport optimized: h5bp.com/viewport %>
  <meta name="viewport" content="width=device-width">
  
  <%= stylesheet_link_tag "static_pages" %>
  <%= stylesheet_link_tag "forms" %>
  <%= stylesheet_link_tag "property" %>
  <%# render "stylesheets" %>


  <%# More ideas for your <head> here: h5bp.com/d/head-Tips %>

  <%# All JavaScript at the bottom, except polyfills %>
  <%= javascript_include_tag "polyfills" %>

  <%= csrf_meta_tag %>
</head>

app/views/application/_header.html.erb
<header id="header">
  <h1>Rent A Home</h1>
</header>

app/views/application/_navigation.html.erb
<ul>
	<li><%= link_to "Home", root_path, :class => 'brand' %></li>
	<li><%= link_to "Rent A Hmone", search_properties_url, :class => 'brand'%></li>
	<% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_sessin_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %> 
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%# http://paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither %>
<%= html_tag :class => "no-js" %>
  <%= render "head" %>

  <body class="<%= controller.controller_name %>">
  	<div id="page">
    	<%= render "chromeframe" %>
	    <%= render "header" %>
	
		<div id="nav"><%= render "navigation" %></div>
	    <div id="main" role="main">
	      <%= render "flashes" %>
	      
	      <%= yield %>
	    </div>
	
	    <%= render "footer" %>
	
	    <%# Javascript at the bottom for fast page loading %>
	    <%= render "javascripts" %>
	</div>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_tag({:controller => "properties" }, :method => "get") do |f|%>

	<fieldset id="rental">
		<legend>Rental Type:</legend>
		<div class="double_column_list">
			<ul>
				<li>
					<%= check_box_tag(:house) %>
					<label for="house">House:</label>
										
				</li>
				<li>
					<%= check_box_tag(:apartment) %>
					<label for="apt">Apartment:</label>	
				</li>
				<li>
					<%= check_box_tag(:townhouse) %>
					<label for="townhouse">Townhouse:</label>						
				</li>

				<li>
					<%= check_box_tag(:condo) %> 
					<label for="condo">Condo:</label>	 			
				</li>
			</ul>
		</div>
	</fieldset>
	
	<fieldset id="price">
		<legend>Price Range:</legend>
		
		<div class="double_column_list">
			<ul>
				<li><label for="min">Min:</label><input type="text" name="min" /></li>
				<li><label for="max">Max:</label><input type="text" name="max" /></li>
			</ul>
		</div>
	</fieldset>
	
	<fieldset id="location">
		<legend>Location:</legend>
		
		<div class="double_column_list">
			<ul>
				<li>
					<label for="city">City:</label>
					<%= collection_select(:search, :city, City.order('name ASC').all, :id, :name) %>	
				<li>
					<label for="state">State:</label>
					<%= collection_select(:search, :state,  State.order('name ASC').all, :abbr, :name) %>		
				</li>
				<li>
					<label for="county">County:</label>
					<%= collection_select(:search, :county, County.order('name ASC').all, :id, :name) %>
				</li>
				<li>
					<label for="zip">Zip:</label>
					<%= collection_select(:search, :zip, Zip.order('zip_code ASC').all, :id, :zip_code) %>
				</li>
			</ul>
	</fieldset>
	
	<fieldset id="rooms">
		<legend>#Rooms and #Bathroom:</legend>
		
		<div class="double_column_list">
			<ul>
				<li>
					<label for="room"># Rooms:</label>
					<%= collection_select(:seach, :room, Room.order('room ASC').all, :id, :room) %>
				</li>
				<li>
					<label for="bathroom"># Bathroom:</label>
					<%= collection_select(:search, :bahtroom, Bathroom.order('bathroom ASC').all, :id, :bathroom) %>
				</li>
	</fieldset>
	
	<fieldset id="pet">
		<legend>Pets:</legend>
		
		<div class="double_column_list">
			<ul>
				<li>
					<%= radio_button_tag(:pet, "cat") %>
					<label for="cat">Cat</label>
					
				</li>
				<li>
					<%= radio_button_tag(:pet, "dog") %>
					<label for="dog">Dog</label>					
				</li>
				<li>
					<%= radio_button_tag(:pet, "both") %>
					<label for="both">Both</label>					
				</li>
				<li>
					<%= radio_button_tag(:pet, "none")%>
					<label for="none">None</label>					
				</li>
			</ul>
	</fieldset>
	<input type="submit" value="Rent A Home" class="button pill">
<% end %>

app/views/properties/index.html.erb
<p>Property Listing:</p>
	<div id="table">
		<div class="th">Rental</div>
		<div class="th">Price</div>
		<div class="th">Address</div>
		<div class="th">City</div>
		<div class="th">State</div>
		<div class="th">Zip</div>
		<div class="th">County</div>
		<div class="th">Pet</div>
		
		<% if @property.blank? %>
		<div class="td_span">There are no results for your search please try a new search. </div>
		<% else 
		@property .each do |p| %>
		<div class="td"><%= p.rental %></div>
		<div class="td"><%= p.price %></div>
		<div class="td"><%= p.address %></div>
		<div class="td"><%= p.city %></div>
		<div class="td"><%= p.state %></div>
		<div class="td"><%= p.zip %></div>
		<div class="td"><%= p.county %></div>
		<div class="td"><%= p.pet %></div>
		<% end 
		end%>
	</div>

app/views/properties/search.html.erb
<h3 class="center_text">You are well on your way to finding your next Home!</h3>

<%= render 'form' %>

app/views/static_pages/home.html.erb
	<p>If you are like me you have had to move at lease once if not more in your life.</p>

	<p>As for me I move ALOT (uhg!). So what do we all do? We jump online faithfully go to our trusted friend Craig.
   Only to get EVREYTHING, from houses to apt to condos and everything in the middle.</p>
   
	<h3>I only want houses! Is that too much to ask for?</h3>
	
	<p>Therefor we all digress to using Google and navigainting to some rents search site that asks us for our name and email
		only to then let us search and send us the results by email or yet give us spam later.</p>
		
	<p>Would it be nice to have a site that just lets you search for what you want, where you want with out jumping the hoops,
		and returs us a list of available proporties we can view NOW?</p>
		
	<h3>Well you are in luck. You can do that right here.</h3>
	
	<p>Use out quick searech below or go to the <%= link_to 'Rent A Home', search_properties_url %> page 
	   for a full search. You can create a <%= link_to 'free account', root_url %> to save the properties
	   you are intrested in, or setup a "search watch" that will email new results as they become 
	   avalibale.</p>
	
	<%= form_tag({:controller => "properties"}, :method => "get") do |f|%>
		<fieldset id="quick_search">
			
			<ul >
				<li>Search by State or Zip</li>
				<li>Must Select State to search by City</li>
			</ul>
			
			<div >
			<ul>
				<li>
					<label for="city">City:</label>
					<%= collection_select(:search, :city, City.order('name ASC').all, :id, :name, :prompt => true) %>
				</li>
				<li>
					<label for="state">State:</label> 
					<%= collection_select(:serach, :state,  State.order('name ASC').all, :abbr, :name, :prompt => true) %>
				</li>
				<li><label>Zip:</label> 
					<%= collection_select(:search, :zip, Zip.order('zip_code ASC').all, :id, :zip_code, :prompt => true) %>
				</li>
			</ul>
			</br>
			<input type="submit" value="Rent A Home" />
		</fieldset>
	
	<% end %>
	

app/views/static_pages/test.html.erb
 /countries.html